# Generated by Django 6.0.7 on 2026-07-20 07:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('directory', '0002_review'),
    ]

    operations = [
        migrations.AddField(
            model_name='business',
            name='banner',
            field=models.ImageField(blank=True, null=True, upload_to='businesses/banners/'),
        ),
        migrations.AddField(
            model_name='business',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='businesses/logos/'),
        ),
    ]
