# Generated by Django 6.0.7 on 2026-07-20 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('directory', '0003_business_banner_business_logo'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='owner_reply',
            field=models.TextField(blank=True, null=True, verbose_name='پاسخ صاحب کسب\u200cوکار'),
        ),
        migrations.AddField(
            model_name='review',
            name='reply_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='تاریخ ثبت پاسخ'),
        ),
    ]
