# Generated by Django 6.0.7 on 2026-07-25 10:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('directory', '0004_review_owner_reply_review_reply_date'),
        ('taxonomy', '0002_category_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='business',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='businesses', to='taxonomy.category'),
        ),
        migrations.AlterField(
            model_name='business',
            name='location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='businesses', to='taxonomy.location'),
        ),
    ]
