# Generated by Django 6.0.7 on 2026-07-25 14:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('directory', '0005_alter_business_category_alter_business_location'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DiscountCampaign',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=50, unique=True, verbose_name='کد معرف')),
                ('discount_percent', models.PositiveIntegerField(blank=True, null=True, verbose_name='درصد تخفیف')),
                ('max_usage', models.PositiveIntegerField(default=10, verbose_name='ظرفیت کل')),
                ('current_usage', models.PositiveIntegerField(default=0, verbose_name='تعداد استفاده شده')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال/غیرفعال')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='campaigns', to='directory.business')),
            ],
        ),
        migrations.CreateModel(
            name='CampaignUsage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('claimed_at', models.DateTimeField(auto_now_add=True, verbose_name='زمان دریافت')),
                ('is_redeemed', models.BooleanField(default=False, verbose_name='آیا در خرید حضوری استفاده شد؟')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='used_campaigns', to=settings.AUTH_USER_MODEL)),
                ('campaign', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='usages', to='directory.discountcampaign')),
            ],
            options={
                'unique_together': {('client', 'campaign')},
            },
        ),
    ]
