# Generated by Django 6.0.7 on 2026-07-25 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('directory', '0006_discountcampaign_campaignusage'),
    ]

    operations = [
        migrations.AddField(
            model_name='business',
            name='instagram_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='business',
            name='latitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='business',
            name='longitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='business',
            name='public_phone',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='business',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='business',
            name='name',
            field=models.CharField(max_length=255),
        ),
    ]
