# Generated by Django 6.0.7 on 2026-07-26 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('directory', '0007_business_instagram_id_business_latitude_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='business',
            name='engagement_count',
            field=models.PositiveIntegerField(default=0, verbose_name='تعاملات ثبت شده (کلیک، تماس و...) '),
        ),
        migrations.AddField(
            model_name='business',
            name='views_count',
            field=models.PositiveIntegerField(default=0, verbose_name='مجموع بازدیدها'),
        ),
        migrations.AlterField(
            model_name='business',
            name='average_rating',
            field=models.FloatField(default=0.0, verbose_name='میانگین امتیازات'),
        ),
    ]
