# Generated by Django 6.0.7 on 2026-07-26 15:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('directory', '0008_business_engagement_count_business_views_count_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SubscriptionPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='نام پلن (مثل برنزی، طلایی)')),
                ('base_discount_percentage', models.PositiveIntegerField(verbose_name='درصد تخفیف پایه')),
                ('price_per_month', models.DecimalField(decimal_places=0, max_digits=10, verbose_name='قیمت ماهانه')),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='CustomerProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plan_expiry_date', models.DateTimeField(blank=True, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='customer_profile', to=settings.AUTH_USER_MODEL)),
                ('active_plan', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='directory.subscriptionplan')),
            ],
        ),
        migrations.CreateModel(
            name='TransactionLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('original_amount', models.DecimalField(decimal_places=0, max_digits=12, verbose_name='مبلغ اولیه فاکتور')),
                ('applied_discount_percentage', models.PositiveIntegerField(verbose_name='درصد تخفیف اعمال شده')),
                ('discount_source', models.CharField(choices=[('SUBSCRIPTION', 'اشتراک VIP'), ('CAMPAIGN', 'کمپین اختصاصی'), ('NONE', 'بدون تخفیف')], max_length=20)),
                ('final_amount', models.DecimalField(decimal_places=0, max_digits=12, verbose_name='مبلغ پرداختی نهایی')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='directory.business')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='purchases', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
