# Generated by Django 6.0.7 on 2026-08-06 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('directory', '0010_userbusinessvisit'),
    ]

    operations = [
        migrations.CreateModel(
            name='SiteContent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('page_type', models.CharField(choices=[('about', 'درباره ما'), ('contact', 'تماس با ما'), ('terms_client', 'قوانین مشتریان'), ('terms_business', 'قوانین کسب و کار')], max_length=20, unique=True, verbose_name='نوع صفحه')),
                ('title', models.CharField(max_length=200, verbose_name='عنوان صفحه')),
                ('content', models.TextField(verbose_name='محتوای صفحه')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'محتوای سایت',
                'verbose_name_plural': 'محتواهای سایت',
            },
        ),
    ]
