# Generated by Django 6.0.7 on 2026-08-06 16:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('directory', '0011_sitecontent'),
    ]

    operations = [
        migrations.CreateModel(
            name='Story',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('media', models.FileField(help_text='عکس یا ویدیوی استوری', upload_to='businesses/stories/%Y/%m/')),
                ('link', models.URLField(blank=True, help_text='لینک اختیاری (مثلا برای Swipe Up)', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stories', to='directory.business')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
