# Generated by Django 6.0.7 on 2026-07-21 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Banner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='عنوان بنر (فقط برای مدیریت)')),
                ('image', models.ImageField(upload_to='cms/banners/', verbose_name='تصویر بنر')),
                ('url', models.URLField(blank=True, null=True, verbose_name='لینک مقصد هنگام کلیک')),
                ('position', models.CharField(choices=[('main_slider', 'اسلایدر اصلی صفحه خانه'), ('sidebar', 'بنر سایدبار'), ('promotional', 'بنر تبلیغاتی بین دسته\u200cبندی\u200cها')], default='main_slider', max_length=50, verbose_name='جایگاه بنر')),
                ('order', models.IntegerField(default=0, verbose_name='ترتیب نمایش')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال برای نمایش؟')),
            ],
            options={
                'verbose_name': 'بنر',
                'verbose_name_plural': 'بنرها',
                'db_table': 'cms_banners',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='Menu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='عنوان منو')),
                ('url', models.CharField(max_length=255, verbose_name='لینک مقصد')),
                ('icon', models.CharField(blank=True, max_length=50, null=True, verbose_name='نام آیکون (برای موبایل)')),
                ('position', models.CharField(choices=[('header', 'هدر (بالای سایت)'), ('footer', 'فوتر (پایین سایت)'), ('mobile', 'منوی موبایل')], default='header', max_length=20, verbose_name='جایگاه')),
                ('order', models.IntegerField(default=0, verbose_name='ترتیب نمایش')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال برای نمایش؟')),
            ],
            options={
                'verbose_name': 'منو',
                'verbose_name_plural': 'منوها',
                'db_table': 'cms_menus',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='SiteSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=100, unique=True, verbose_name='کلید تنظیمات (مثلاً: footer_about_text)')),
                ('value', models.TextField(verbose_name='مقدار (متن نمایشی)')),
                ('description', models.CharField(blank=True, max_length=255, null=True, verbose_name='توضیحات ادمین')),
            ],
            options={
                'verbose_name': 'تنظیمات متن',
                'verbose_name_plural': 'تنظیمات متون سایت',
                'db_table': 'cms_site_settings',
            },
        ),
    ]
