# Generated by Django 6.0.7 on 2026-07-23 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesetting',
            name='hero_align',
            field=models.CharField(blank=True, choices=[('right', 'راست\u200cچین'), ('center', 'وسط\u200cچین'), ('left', 'چپ\u200cچین')], max_length=10, null=True, verbose_name='چیدمان متن هیرو (انتخابی)'),
        ),
        migrations.AddField(
            model_name='sitesetting',
            name='hero_size',
            field=models.CharField(blank=True, choices=[('sm', 'کوچک'), ('md', 'متوسط'), ('lg', 'بزرگ')], max_length=10, null=True, verbose_name='سایز متن هیرو (انتخابی)'),
        ),
        migrations.AlterField(
            model_name='sitesetting',
            name='value',
            field=models.TextField(blank=True, null=True, verbose_name='مقدار (متن نمایشی)'),
        ),
    ]
