# Generated by Django 6.0.7 on 2026-07-23 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0002_sitesetting_hero_align_sitesetting_hero_size_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sitesetting',
            name='hero_align',
        ),
        migrations.RemoveField(
            model_name='sitesetting',
            name='hero_size',
        ),
        migrations.AlterField(
            model_name='sitesetting',
            name='value',
            field=models.TextField(verbose_name='مقدار (متن نمایشی)'),
        ),
    ]
