# Generated by Django 6.0.7 on 2026-07-21 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taxonomy', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='price',
            field=models.BigIntegerField(default=0, verbose_name='قیمت (تومان)'),
        ),
    ]
