# Generated by Django 6.0.7 on 2026-08-09 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taxonomy', '0002_category_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='icon',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='آیکون یا ایموجی'),
        ),
    ]
