# Generated by Django 6.0.7 on 2026-07-20 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('identity', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('ADMIN', 'مدیر کل'), ('BUSINESS_OWNER', 'صاحب کسب\u200cوکار'), ('CLIENT', 'مشتری')], default='CLIENT', max_length=20),
        ),
    ]
