# Generated by Django 6.0.7 on 2026-07-25 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('identity', '0002_user_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='full_name',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='نام و نام خانوادگی'),
        ),
        migrations.AddField(
            model_name='user',
            name='is_shahkar_verified',
            field=models.BooleanField(default=False, verbose_name='تاییدیه شاهکار'),
        ),
        migrations.AddField(
            model_name='user',
            name='national_id',
            field=models.CharField(blank=True, max_length=10, null=True, unique=True, verbose_name='کد ملی'),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('ADMIN', 'مدیر'), ('BUSINESS_OWNER', 'صاحب کسب\u200cوکار'), ('CLIENT', 'مشتری')], default='CLIENT', max_length=20),
        ),
    ]
